# Generated by Django 4.1.3 on 2022-12-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project_Data', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('details', models.TextField()),
                ('Client_Previous_Payout', models.SmallIntegerField()),
                ('Production_Suggested_Project_Advance', models.SmallIntegerField()),
                ('Latest_Project_Advance', models.SmallIntegerField()),
                ('Latest_Client_Payout_Status', models.CharField(choices=[('In-Progress', 'In-Progress'), ('Done', 'Done')], default=1, max_length=100)),
                ('Total_Client_Payout', models.SmallIntegerField()),
                ('Contract_Document_Signing_Status', models.CharField(choices=[('SM', 'SM'), ('FM', 'FM')], default=1, max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Project_Data.project_table')),
            ],
        ),
    ]
