# Generated by Django 4.1.3 on 2022-12-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='worklink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worklink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='artist_table',
            fields=[
                ('artist_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='images')),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('otherperformart', models.TextField()),
                ('social_link_f', models.CharField(max_length=100)),
                ('social_link_l', models.CharField(max_length=100)),
                ('social_link_p', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('manger', models.BooleanField()),
                ('budget_range', models.TextField()),
                ('budget_idea', models.TextField()),
                ('am_note', models.TextField()),
                ('pm_note', models.TextField()),
                ('rating', models.IntegerField()),
                ('worklink', models.ManyToManyField(to='admin_panel.worklink')),
            ],
        ),
    ]
