# Generated by Django 4.1.3 on 2022-12-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_worklink_artist_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='genre_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanuage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist_table',
            name='worklink',
        ),
        migrations.RemoveField(
            model_name='artist_table',
            name='language',
        ),
        migrations.RemoveField(
            model_name='artist_table',
            name='skill',
        ),
        migrations.AddField(
            model_name='artist_table',
            name='location',
            field=models.ManyToManyField(to='admin_panel.location'),
        ),
        migrations.AddField(
            model_name='artist_table',
            name='language',
            field=models.ManyToManyField(to='admin_panel.language'),
        ),
        migrations.AddField(
            model_name='artist_table',
            name='skill',
            field=models.ManyToManyField(to='admin_panel.skill'),
        ),
    ]
