# Generated by Django 4.1.3 on 2022-12-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_genre_table_language_location_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_fee', models.IntegerField()),
                ('Production_Advance', models.IntegerField()),
                ('Negotiated_Advance', models.IntegerField()),
                ('Final_Advance', models.IntegerField()),
                ('Advance_Status', models.CharField(choices=[('In-Progress', 'In-Progress'), ('Done', 'Done')], default=1, max_length=100)),
                ('Assigned_Artists_Payouts', models.CharField(max_length=100)),
                ('Assigned_Artists_Advance_Payout_Status', models.CharField(choices=[('In-Progress', 'In-Progress'), ('Done', 'Done')], default=1, max_length=100)),
                ('Final_Fee_Settlement_Status', models.BooleanField()),
                ('Post_Project_Client_Total_Payout', models.IntegerField()),
                ('project_fee_status', models.CharField(choices=[('SM', 'SM'), ('FM', 'FM')], default=1, max_length=100)),
                ('client_id', models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.client_table')),
                ('project_id', models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.project_table')),
            ],
        ),
        migrations.CreateModel(
            name='project_demos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist_Status', models.CharField(choices=[('Shorlisted', 'Shorlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default=1, max_length=100)),
                ('comment', models.TextField()),
                ('artist', models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.artist_table')),
                ('demo_work', models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.worklink')),
                ('project', models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.project_table')),
            ],
        ),
        migrations.CreateModel(
            name='artist_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Other_Performing_Art_Details', models.TextField()),
                ('min_budget', models.IntegerField()),
                ('max_budget', models.IntegerField()),
                ('budget', models.TextField()),
                ('production_hiring', models.IntegerField()),
                ('servicing_hiring', models.IntegerField()),
                ('target', models.IntegerField()),
                ('comments', models.TextField()),
                ('hiring_process', models.CharField(choices=[('In-Progress', 'In-Progress'), ('Done', 'Done')], default=1, max_length=100)),
                ('genre', models.ManyToManyField(to='admin_panel.genre_table')),
                ('language', models.ManyToManyField(to='admin_panel.language')),
                ('location', models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.location')),
                ('project', models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.project_table')),
                ('skill', models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.skill')),
            ],
        ),
        migrations.CreateModel(
            name='artist_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pre_Project_Production_Feedbacks', models.TextField()),
                ('On_Project_Production_Feedbacks', models.TextField()),
                ('Post_Production_Client_Feedbacks', models.TextField()),
                ('artist', models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.artist_table')),
            ],
        ),
    ]
