# Generated by Django 4.1.3 on 2022-12-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project_Data', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='images')),
                ('age', models.SmallIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('otherperformart', models.TextField()),
                ('social_link_f', models.CharField(max_length=100)),
                ('social_link_l', models.CharField(max_length=100)),
                ('social_link_p', models.CharField(max_length=100)),
                ('number', models.SmallIntegerField()),
                ('manger', models.BooleanField()),
                ('budget_range', models.TextField()),
                ('budget_idea', models.TextField()),
                ('am_note', models.TextField()),
                ('pm_note', models.TextField()),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1, max_length=2)),
                ('genre', models.ManyToManyField(to='Project_Data.genre')),
                ('language', models.ManyToManyField(to='Project_Data.language')),
                ('location', models.ManyToManyField(to='Project_Data.location')),
                ('skill', models.ManyToManyField(to='Project_Data.skill')),
            ],
        ),
        migrations.CreateModel(
            name='worklink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worklink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDemos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist_Status', models.CharField(choices=[('Shorlisted', 'Shorlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default=1, max_length=100)),
                ('comment', models.TextField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artist.artisttable')),
                ('demo_work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artist.worklink')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Project_Data.project_table')),
            ],
        ),
        migrations.AddField(
            model_name='artisttable',
            name='worklink',
            field=models.ManyToManyField(to='artist.worklink'),
        ),
        migrations.CreateModel(
            name='ArtistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_Performing_Art_Details', models.TextField()),
                ('min_budget', models.SmallIntegerField()),
                ('max_budget', models.SmallIntegerField()),
                ('budget', models.TextField()),
                ('production_hiring', models.SmallIntegerField()),
                ('servicing_hiring', models.SmallIntegerField()),
                ('target', models.SmallIntegerField()),
                ('comments', models.TextField()),
                ('hiring_process', models.CharField(choices=[('In-Progress', 'In-Progress'), ('Done', 'Done')], default=1, max_length=100)),
                ('genre', models.ManyToManyField(to='Project_Data.genre')),
                ('language', models.ManyToManyField(to='Project_Data.language')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Project_Data.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Project_Data.project_table')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Project_Data.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pre_Project_Production_Feedbacks', models.TextField()),
                ('On_Project_Production_Feedbacks', models.TextField()),
                ('Post_Production_Client_Feedbacks', models.TextField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artist.artisttable')),
            ],
        ),
    ]
