# Generated by Django 4.1.3 on 2022-12-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artist', '0001_initial'),
        ('Artist_Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisttable',
            name='genre',
            field=models.ManyToManyField(to='Artist_Project.genre'),
        ),
        migrations.AddField(
            model_name='artisttable',
            name='language',
            field=models.ManyToManyField(to='Artist_Project.language'),
        ),
        migrations.AddField(
            model_name='artisttable',
            name='location',
            field=models.ManyToManyField(to='Artist_Project.location'),
        ),
        migrations.AddField(
            model_name='artisttable',
            name='skill',
            field=models.ManyToManyField(to='Artist_Project.skill'),
        ),
        migrations.AddField(
            model_name='artisttable',
            name='worklink',
            field=models.ManyToManyField(to='Artist.worklink'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='genre',
            field=models.ManyToManyField(to='Artist_Project.genre'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='language',
            field=models.ManyToManyField(to='Artist_Project.language'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Artist_Project.location'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Artist_Project.project_table'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Artist_Project.skill'),
        ),
        migrations.AddField(
            model_name='artistfeedback',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Artist.artisttable'),
        ),
    ]
