# Generated by Django 4.1.3 on 2022-12-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artist_Project', '0001_initial'),
        ('Artist', '0002_projectdemos_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistrequest',
            name='genre',
            field=models.ManyToManyField(related_name='Genre', to='Artist_Project.genre'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='language',
            field=models.ManyToManyField(related_name='Language', to='Artist_Project.language'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='location',
            field=models.ManyToManyField(related_name='Location', to='Artist_Project.location'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Project_Table1', to='Artist_Project.project_table'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='skill',
            field=models.ManyToManyField(related_name='Skill', to='Artist_Project.skill'),
        ),
    ]
