# Generated by Django 4.1.3 on 2022-12-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist_Project', '0001_initial'),
        ('Artist', '0003_artistrequest_genre_artistrequest_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisttable',
            name='genre',
            field=models.ManyToManyField(related_name='Genre1', to='Artist_Project.genre'),
        ),
        migrations.AddField(
            model_name='artisttable',
            name='language',
            field=models.ManyToManyField(related_name='Language1', to='Artist_Project.language'),
        ),
        migrations.AddField(
            model_name='artisttable',
            name='location',
            field=models.ManyToManyField(related_name='Location1', to='Artist_Project.location'),
        ),
        migrations.AddField(
            model_name='artisttable',
            name='skill',
            field=models.ManyToManyField(related_name='Skill1', to='Artist_Project.skill'),
        ),
    ]
